<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BooksTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('books')->insert([
            [
                'user_id' => 1,
                'category_id' => 1,
                'item_name' => '問題解決力を鍛える!アルゴリズムとデータ構造',
                'item_review' => '全般的な内容としては満足していて、特に、多くの演習問題については出典の AtCoder の対応する問題が示されているため、自分の答案コードが正しいのか明確に判別できるようになっている点が非常に気に入っております。',
                'item_number' => 1,
                'item_amount' => 3000,
                'published_at' => '2020-10-02 00:00:00',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'user_id' => 3,
                'category_id' => 2,
                'item_name' => '運用改善の教科書 ~クラウド時代にも困らない、変化に迅速に対応するためのシステム運用ノウハウ',
                'item_review' => 'システム運用はいま、転換期を迎えています。DX(デジタルトランスフォーメーション)の推進やクラウドサービスの普及により、運用に求められる考え方は急速に変化しました。クラウドをどう管理していくのか? サービスマネジメントに最適な運用とは? セキュリティへの意識は今のままでいいのか? 時代の最先端に常にキャッチアップできる運用チームを作り上げるための、継続的な運用改善ノウハウをまとめました。',
                'item_number' => 2,
                'item_amount' => 2980,
                'published_at' => '2024-04-12 00:00:00',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'user_id' => 4,
                'category_id' => 3,
                'item_name' => 'AWS運用入門',
                'item_review' => null,
                'item_number' => 3,
                'item_amount' => 3300,
                'published_at' => '2020-02-12 00:00:00',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'user_id' => 1,
                'category_id' => 3,
                'item_name' => 'アルゴリズムとデータ構造',
                'item_review' => null,
                'item_number' => 1,
                'item_amount' => 3000,
                'published_at' => '2024-04-23 00:00:00',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'user_id' => 3,
                'category_id' => 4,
                'item_name' => '運用改善の教科書',
                'item_review' => null,
                'item_number' => 2,
                'item_amount' => 2980,
                'published_at' => '2024-04-12 00:00:00',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'user_id' => 4,
                'category_id' => 1,
                'item_name' => 'AWS運用入門',
                'item_review' => null,
                'item_number' => 3,
                'item_amount' => 3300,
                'published_at' => '2020-02-12 00:00:00',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'user_id' => 4,
                'category_id' => 3,
                'item_name' => 'AWS運用入門',
                'item_review' => null,
                'item_number' => 3,
                'item_amount' => 3300,
                'published_at' => '2020-02-12 00:00:00',
                'created_at' => '2024-04-21 13:39:04',
                'updated_at' => '2024-04-21 13:39:04',
            ],
            [

                'user_id' => 4,
                'category_id' => 2,
                'item_name' => 'AWS運用入門',
                'item_review' => null,
                'item_number' => 3,
                'item_amount' => 3300,
                'published_at' => '2020-02-12 00:00:00',
                'created_at' => '2024-04-21 13:42:23',
                'updated_at' => '2024-04-21 13:42:23',
            ],
            [
                'user_id' => 4,
                'category_id' => 2,
                'item_name' => 'AWS運用入門',
                'item_review' => null,
                'item_number' => 3,
                'item_amount' => 3300,
                'published_at' => '2020-02-12 00:00:00',
                'created_at' => '2024-04-21 14:10:12',
                'updated_at' => '2024-04-21 14:10:12',
            ],
            [
                'user_id' => 4,
                'category_id' => 1,
                'item_name' => 'ほげほげほげAWS',
                'item_review' => null,
                'item_number' => 8888,
                'item_amount' => 555555,
                'published_at' => '1980-05-06 00:00:00',
                'created_at' => '2024-04-22 02:07:39',
                'updated_at' => '2024-04-22 02:07:39',
            ],
            [
                'user_id' => 4,
                'category_id' => 3,
                'item_name' => 'AWS運用入門ああ',
                'item_review' => null,
                'item_number' => 40,
                'item_amount' => 555555,
                'published_at' => '1980-05-06 00:00:00',
                'created_at' => '2024-04-22 04:10:28',
                'updated_at' => '2024-04-22 04:10:28',
            ],
            [
                'user_id' => 4,
                'category_id' => 4,
                'item_name' => 'AWS運用入門',
                'item_review' => null,
                'item_number' => 3,
                'item_amount' => 3300,
                'published_at' => '2020-02-12 00:00:00',
                'created_at' => '2024-04-22 04:13:29',
                'updated_at' => '2024-04-22 04:13:29',
            ],
            [
                'user_id' => 4,
                'category_id' => 1,
                'item_name' => 'AWS運用入門',
                'item_review' => null,
                'item_number' => 3,
                'item_amount' => 3300,
                'published_at' => '2020-02-12 00:00:00',
                'created_at' => '2024-04-22 04:14:15',
                'updated_at' => '2024-04-22 04:14:15',
            ],
            [
                'user_id' => 4,
                'category_id' => 1,
                'item_name' => 'AWS運用入門あああ',
                'item_review' => null,
                'item_number' => 8888,
                'item_amount' => 555555,
                'published_at' => '1980-05-06 00:00:00',
                'created_at' => '2024-04-22 04:14:24',
                'updated_at' => '2024-04-22 04:14:24',
            ],
            [
                'user_id' => 4,
                'category_id' => 1,
                'item_name' => 'AWS運用入門',
                'item_review' => null,
                'item_number' => 3,
                'item_amount' => 3300,
                'published_at' => '2020-02-12 00:00:00',
                'created_at' => '2024-04-22 04:29:52',
                'updated_at' => '2024-04-22 04:29:52',
            ],
            [
                'user_id' => 4,
                'category_id' => 1,
                'item_name' => 'AWS運用入門あああ',
                'item_review' => null,
                'item_number' => 8888,
                'item_amount' => 555555,
                'published_at' => '1980-05-06 00:00:00',
                'created_at' => '2024-04-22 04:30:45',
                'updated_at' => '2024-04-22 04:30:45',
            ],
            [
                'user_id' => 4,
                'category_id' => 1,
                'item_name' => 'ほげほげほげ',
                'item_review' => 'これはすごい',
                'item_number' => 8888,
                'item_amount' => 555555,
                'published_at' => '1980-05-06 00:00:00',
                'created_at' => '2024-04-22 04:32:28',
                'updated_at' => '2024-04-22 04:32:28',
            ],
            [
                'user_id' => 4,
                'category_id' => 1,
                'item_name' => 'ほげほげほげ',
                'item_review' => 'これはすごいぞ',
                'item_number' => 8888,
                'item_amount' => 555555,
                'published_at' => '2024-04-20 00:00:00',
                'created_at' => '2024-04-22 05:17:34',
                'updated_at' => '2024-04-22 05:17:34',
            ],
            [
                'user_id' => 4,
                'category_id' => 1,
                'item_name' => 'ほげほげほげ',
                'item_review' => 'これはすごいぞ',
                'item_number' => 8888,
                'item_amount' => 555555,
                'published_at' => '2024-04-24 00:00:00',
                'created_at' => '2024-04-22 05:18:07',
                'updated_at' => '2024-04-22 05:18:07',
            ],
            [
                'user_id' => 4,
                'category_id' => 1,
                'item_name' => 'ほげほげほげ',
                'item_review' => 'これはすごいぞ',
                'item_number' => 8888,
                'item_amount' => 555555,
                'published_at' => '2024-04-27 00:00:00',
                'created_at' => '2024-04-22 05:18:41',
                'updated_at' => '2024-04-22 05:18:41',
            ],
            [
                'user_id' => 4,
                'category_id' => 7,
                'item_name' => 'ログ分析の教科書',
                'item_review' => 'ログ分析をしてセキュリティ対策ができる本。\r\nセキュリティエンジニアなら必読の一冊！',
                'item_number' => 8888,
                'item_amount' => 3260,
                'published_at' => '2024-04-19 00:00:00',
                'created_at' => '2024-04-22 05:19:52',
                'updated_at' => '2024-04-22 05:19:52',
            ],
            [
                'user_id' => 4,
                'category_id' => 1,
                'item_name' => 'ほげほげほげ',
                'item_review' => 'これはすごいぞ',
                'item_number' => 8888,
                'item_amount' => 555555,
                'published_at' => '2024-04-06 00:00:00',
                'created_at' => '2024-04-22 05:26:08',
                'updated_at' => '2024-04-22 05:26:08',
            ],
            [
                'user_id' => 4,
                'category_id' => 1,
                'item_name' => 'AWS運用入門あああ',
                'item_review' => 'これはすごい',
                'item_number' => 8888,
                'item_amount' => 555555,
                'published_at' => '2024-04-13 00:00:00',
                'created_at' => '2024-04-22 06:10:26',
                'updated_at' => '2024-04-22 06:10:26',
            ],
            [
                'user_id' => 4,
                'category_id' => 9,
                'item_name' => 'AWS運用入門あああ',
                'item_review' => 'とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！とてもすごい本です！',
                'item_number' => 8888,
                'item_amount' => 555555,
                'published_at' => '2024-04-06 00:00:00',
                'created_at' => '2024-04-22 07:25:00',
                'updated_at' => '2024-04-22 09:03:00',
            ],
        ]);
    }
}

